name: sync

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/BerriAI/litellm.git
          git fetch upstream
      - name: Sync upstream branch
        run: |
          git checkout upstream
          git reset --hard upstream/main
          git push -f origin upstream
      - name: Sync main branch
        run: |
          git checkout main
          git merge upstream/main          
          git push origin main
